config/routes.rb
Rails.application.routes.draw do
  resources :todo_items, only: [:create, :edit, :update, :destroy]

  get 'static_pages/top'
  root :to => 'static_pages#top'

  get 'todo' => 'todo_lists#list', :as => :todo

  resources :users
  resources :user_sessions

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :todo_tags
  has_many :todo_items, through: :todo_tags

  validates :text, presence: true
  validates :text, uniqueness: true
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :user, :inverse_of => :todo_items
  has_many :todo_tags
  has_many :tags, through: :todo_tags

  validates :text, presence: true

  after_save :manage_tag

  def self.search_by_tag(tag_text)
    unless tag_text.nil?
      joins(:tags).where(tags: {text: tag_text.sub("#", "")})
    else
      all
    end
  end

  private

  def manage_tag
    text = self[:text]
    tags = []
    text.scan(/#[^#\s]+/) do |t|
      t.sub!("#", "")
      tags << Tag.find_or_create_by(text:t)
    end
    self.tags = tags
  end
end

app/models/todo_tag.rb
class TodoTag < ActiveRecord::Base
  belongs_to :todo_item
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :todo_items, dependent: :destroy, inverse_of: :user

  validates :email, presence: true
  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true

  def uniq_tag
    Tag.joins(:todo_items)
      .where(todo_items:{user_id: self.id}).uniq
      .order(updated_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login

  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_filter :require_login

  layout "top"

  def top
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET /todo_items
  # GET /todo_items.json
  def index
    @todo_items = TodoItem.all
  end

  # GET /todo_items/1
  # GET /todo_items/1.json
  def show
  end

  # GET /todo_items/new
  def new
    @todo_item = TodoItem.new
  end

  # GET /todo_items/1/edit
  def edit
  end

  # POST /todo_items
  # POST /todo_items.json
  def create
    @todo_item = current_user.todo_items.create(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to todo_path, notice: 'Todo item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { redirect_to todo_path, alert:@todo_item.errors.full_messages }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_items/1
  # PATCH/PUT /todo_items/1.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to todo_path, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.html { render :edit }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to todo_path, notice: 'Todo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      params.require(:todo_item).permit(:text, :finished)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController

  def list
    @todo_items = current_user.todo_items
      .search_by_tag(params[:tag]).order(updated_at: :desc)
    @new_todo = TodoItem.new
    @tags = current_user.uniq_tag
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_to(:todo, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_path, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, only: [:index, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to :users, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        flash[:alert] = @user.errors
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="ja"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "ToDo"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"

  body
    .navbar.navbar-default.navbar-static-top
      .container
        .navbar-header
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href=root_url ToDo

        .collapse.navbar-collapse
          .navbar-collapse.collapse.navbar-responsive-collapse
            - if current_user
              = form_tag(logout_path, method: :post, class:"navbar-form navbar-right") do
                button.btn.btn-default.navbar-btn Logout

    .container
      .row
        .col-lg-12
          = bootstrap_flash
      = yield

app/views/layouts/top.html.slim
doctype html
html lang="ja"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "ToDo"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"

  body
    nav.navbar.navbar-default.navbar-static-top
      .container
        a.navbar-brand href=root_url ToDo

    header
      .container
        .row
          .col-lg-12
            = bootstrap_flash
        = yield

app/views/static_pages/top.html.slim
header
  .row
    .page-header
      h1 ToDo
  p.text-right
      a> href=new_user_url role="button" Register
      | or
      a< href=login_url Login

app/views/todo_items/_form.html.slim
= form_for @todo_item, :html => {class: 'form-inline'} do |f|
  - if @todo_item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@todo_item.errors.count, "error")} prohibited this todo_item from being saved:"
      ul
        - @todo_item.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :text, "todo"
    = f.text_field :text, class: 'form-control'

  .checkbox
    = f.check_box :finished
    = f.label :finished

  .form-group
    = f.submit "update", class: "btn btn-default"

app/views/todo_items/edit.html.slim
.row
  .col-lg-12

    h1 Editing Todo

    == render 'form'

    = link_to 'Back', todo_path

app/views/todo_items/index.html.slim
h1 Listing todo_items

table
  thead
    tr
      th Text
      th Finished
      th
      th
      th

  tbody
    - @todo_items.each do |todo_item|
      tr
        td = todo_item.text
        td = todo_item.finished
        td = link_to 'Show', todo_item
        td = link_to 'Edit', edit_todo_item_path(todo_item)
        td = link_to 'Destroy', todo_item, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Todo item', new_todo_item_path

app/views/todo_items/new.html.slim
h1 New todo_item

== render 'form'

= link_to 'Back', todo_items_path

app/views/todo_items/show.html.slim
p#notice = notice

p
  strong Text:
  = @todo_item.text
p
  strong Finished:
  = @todo_item.finished

= link_to 'Edit', edit_todo_item_path(@todo_item)
'|
= link_to 'Back', todo_items_path

app/views/todo_lists/list.html.slim
.row
  .col-lg-12
    = form_for @new_todo, :html => {class: 'form-inline'} do |f|
      .form-group
        = f.label :text, 'new todo: '
        = f.text_field :text, class: 'form-control'
      = f.submit "add", class: "btn btn-default"

.row
  .col-lg-10
    h3 Todo
    table.table

      tbody
        - @todo_items.each do |todo|
          tr
            td = link_to todo.text, edit_todo_item_path(todo)
            - if todo.finished
                td finished
            - else
                td ongoing
            td = todo.updated_at
            td = link_to '×', todo, data: {:confirm => 'Are you sure?'}, :method => :delete

  .col-lg-2
    h5 Tags

    ul.list-group
      - @tags.each do |tag|
        li.list-group-item
          =link_to tag.text, todo_path(tag: tag.text)

    =link_to 'clear tag search', todo_path(tag: nil)

app/views/user_sessions/_form.html.slim
= form_tag user_sessions_path, :method => :post, class: "form-inline" do
  .form-group
    = label_tag :email
    = text_field_tag :email, '', class: "form-control", autofocus: true
  .form-group
    = label_tag :password
    = password_field_tag :password, '', class:"form-control"
  = submit_tag "Login", class: "btn btn-default"

app/views/user_sessions/create.html.slim
h1 UserSessions#create
p Find me in app/views/user_sessions/create.html.slim

app/views/user_sessions/destroy.html.slim
h1 UserSessions#destroy
p Find me in app/views/user_sessions/destroy.html.slim

app/views/user_sessions/new.html.slim
h1 Login
= render 'form'

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :email
    = f.text_field :email, class: "form-control", autofocus: true
  .form-group
    = f.label :password
    = f.password_field :password, class: "form-control"
  .form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: "form-control"
  .actions = f.submit class: "btn btn-default"

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Email
      th Crypted password
      th Salt
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.email
        td = user.crypted_password
        td = user.salt
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 Register user

== render 'form'

app/views/users/show.html.slim
p#notice = notice

p
  strong Email:
  = @user.email
p
  strong Crypted password:
  = @user.crypted_password
p
  strong Salt:
  = @user.salt

= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path